name: Test push

on:
  push:
    branches:
      '**'

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.11.3'
        otp-version: '23.2'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get
      shell: bash

    - name: Compile project
      run: |
        MIX_ENV=test mix compile --warnings-as-errors
        MIX_ENV=dev mix compile --warnings-as-errors
        MIX_ENV=prod mix compile --warnings-as-errors
      shell: bash

    - name: Check code format
      run: mix format --check-formatted
      shell: bash

    - name: Run dialyzer
      run: mix dialyzer
      shell: bash

    - name: Run tests
      run: mix test
      shell: bash
